In [1]:
import pandas as pd
import numpy as np
from unicodedata import normalize
import matplotlib.pyplot as plt


%matplotlib inline

In [2]:
dfTRT = pd.read_html('https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M')
len(dfTRT)

3

In [3]:
dfTRT = dfTRT[0]
dfTRT

,Postal Code,Borough,Neighbourhood
0,M1A,Not assigned,Not assigned
1,M2A,Not assigned,Not assigned
2,M3A,North York,Parkwoods
3,M4A,North York,Victoria Village
4,M5A,Downtown Toronto,"Regent Park, Harbourfront"
...,...,...,...
175,M5Z,Not assigned,Not assigned
176,M6Z,Not assigned,Not assigned
177,M7Z,Not assigned,Not assigned
178,M8Z,Etobicoke,"Mimico NW, The Queensway West, South of Bloor,..."
179,M9Z,Not assigned,Not assigned

In [4]:
dfTRT.groupby(by = 'Borough').agg('count')

                  Postal Code  Neighbourhood
Borough
Central Toronto             9              9
Downtown Toronto           19             19
East Toronto                5              5
East York                   5              5
Etobicoke                  12             12
Mississauga                 1              1
North York                 24             24
Not assigned               77             77
Scarborough                17             17
West Toronto                6              6
York                        5              5

In [5]:
rows = len(dfTRT.index)
dropped = 0
for i in range (0, rows):
    if dfTRT.at[i, 'Borough'] == 'Not assigned':
        dfTRT.drop(i, inplace = True)
        rows = rows - 1
        dropped = dropped +1
print('Rows Remaining: ', len(dfTRT.index), 'Rows Dropped: ', dropped)
dfTRT.reset_index(inplace = True)

Rows Remaining:  103 Rows Dropped:  77

In [6]:

for i in range (0, rows):
    if dfTRT.at[i, 'Neighbourhood'] == 'Not assigned':
       
        dfTRT.at[i, 'Neighbourhood'] = dfTRT.at[i, 'Borough']

,index,Postal Code,Borough,Neighbourhood
0,2,M3A,North York,Parkwoods
1,3,M4A,North York,Victoria Village
2,4,M5A,Downtown Toronto,"Regent Park, Harbourfront"
3,5,M6A,North York,"Lawrence Manor, Lawrence Heights"
4,6,M7A,Downtown Toronto,"Queen's Park, Ontario Provincial Government"